services:
  db:
    image: postgres:16
    container_name: support_ticket_db
    environment:
      POSTGRES_USER: support_user
      POSTGRES_PASSWORD: support_password
      POSTGRES_DB: support_tickets
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: